# Generated by Django 4.1.1 on 2024-03-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_auto_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='kick_off_hour',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='rule',
            name='kick_off_minute',
            field=models.JSONField(default=list),
        ),
    ]
