# Generated by Django 4.1.1 on 2024-03-02 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_fixture_round_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='round_number',
        ),
    ]
