# Generated by Django 4.1.1 on 2024-03-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_rename_kickoff_fixture_kickofftime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='KickoffTime',
            field=models.TimeField(),
        ),
    ]
