# Generated by Django 4.1.1 on 2024-03-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_alter_fixture_kickofftime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='KickoffTime',
        ),
    ]
